apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/eka43/k8s_cluster.git 
      revision: HEAD
      directories:
      - path: cluster-addons/*
  template:
    metadata:
      name: '{{.path.segments[0]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/eka43/k8s_cluster.git 
        targetRevision: HEAD
        path: '{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
