apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: prometheus
    version: 14.4.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: falco
    version: 1.15.3
    repository: https://falcosecurity.github.io/charts
    falcosidekick:
      enabled: true
    webui:
      enabled: true
